---
# Location where configuration files will be stored.
config_dir: '~'

# Pi-hole configuration.
pihole_enable: false
#pihole_hostname: pihole
#pihole_timezone: America/Chicago
#pihole_password: "change-this-password"

# Internet monitoring configuration.
monitoring_enable: true
monitoring_speedtest_interval: 3m
monitoring_ping_interval: 5s
monitoring_ping_hosts:  # [URL];[HUMAN_READABLE_NAME]
  - https://nas.int.stangl.co.za/;NAS-Media
  - https://nas-storage.int.stangl.co.za/;NAS-Storage
  - https://gateway.stangl.co.za;UDM-Gateway
  - https://cloudkey.int.stangl.co.za;Unifi-Protect
  - https://hass.int.stangl.co.za;Home-Assistant
  - https://grafana.int.stangl.co.za;Grafana
  - http://pihole.int.stangl.co.za;Pi-Hole

monitoring_lab_hosts:  # [URL];[HUMAN_READABLE_NAME]
  - 192.168.88.245;lab-kvm-01
  - 192.168.88.246;lab-kvm-02
  - 192.168.88.247;lab-kvm-03
  - 192.168.88.248;lab-kvm-04
  - 192.168.88.121;k8s-master-01
  - 192.168.88.122;k8s-master-02
  - 192.168.88.123;k8s-master-03
  - 192.168.88.124;k8s-master-04
  - 192.168.88.125;k8s-master-05
  - 192.168.88.131;k8s-node-01
  - 192.168.88.132;k8s-node-02
  - 192.168.88.133;k8s-node-03
  - 192.168.88.134;k8s-node-04
  - 192.168.88.135;k8s-node-05

monitoring_essential_hosts:  # [URL];[HUMAN_READABLE_NAME]
  - cloudkey.int.stangl.co.za;CloudKey-NVR
  - pihole.int.stangl.co.za;Pi-Hole
  - gateway.stangl.co.za;UDM-Gateway
  - hass.int.stangl.co.za;Home-Assistant

# Shelly Plug configuration. (Also requires `monitoring_enable`)
shelly_enable: true
#shelly_plug_hostname: 192.168.88.34
#shelly_plug_http_username: username
#shelly_plug_http_password: "password"

# AirGradient configuration. (Also requires `monitoring_enable`)
airgradient_enable: false

# Starlink configuration. (Also requires `monitoring_enable`)
starlink_enable: false
