---
# Location where configuration files will be stored.
config_dir: '~'

# Pi-hole configuration.
pihole_enable: true
pihole_hostname: pihole
pihole_timezone: Africa/Johannesburg
pihole_password: "JPdk11Kv"
pihole_web_port: 8080
pihole_image_tag: 2023.05.1

# Internet monitoring configuration.
monitoring_enable: true
monitoring_speedtest_interval: 3m
monitoring_ping_interval: 5s
monitoring_ping_hosts:  # [URL];[HUMAN_READABLE_NAME]
  - https://nas.int.stangl.co.za/;NAS-Media
  - https://nas-storage.int.stangl.co.za/;NAS-Storage
  - https://gateway.stangl.co.za;UDM-Gateway
  - https://cloudkey.int.stangl.co.za;Unifi-Protect
  - https://hass.int.stangl.co.za;Home-Assistant
  - https://grafana.int.stangl.co.za;Grafana
  - https://pihole.int.stangl.co.za;Pi-Hole
  - http://stangl-solar.int.stangl.co.za;Solar-IO-Home
  - http://ascendant-solar.int.stangl.co.za;Solar-IO-Office

monitoring_lab_hosts:  # [URL];[HUMAN_READABLE_NAME]
  - 192.168.88.245;lab-kvm-01
  - 192.168.88.246;lab-kvm-02
  - 192.168.88.247;lab-kvm-03
  - 192.168.88.248;lab-kvm-04
  - 192.168.88.121;k8s-master-01
  - 192.168.88.122;k8s-master-02
  - 192.168.88.123;k8s-master-03
  - 192.168.88.124;k8s-master-04
  - 192.168.88.125;k8s-master-05
  - 192.168.88.131;k8s-node-01
  - 192.168.88.132;k8s-node-02
  - 192.168.88.133;k8s-node-03
  - 192.168.88.134;k8s-node-04
  - 192.168.88.135;k8s-node-05

monitoring_essential_hosts:  # [URL];[HUMAN_READABLE_NAME]
  - cloudkey.int.stangl.co.za;CloudKey-NVR
  - gateway.stangl.co.za;UDM-Gateway
  - hass.int.stangl.co.za;Home-Assistant
  - ascendant-solar.int.stangl.co.za;Solar-IO-Office
  - stangl-solar.int.stangl.co.za;Solar-IO-Home
  - zimaboard.int.stangl.co.za;Zimaboard

# Shelly Plug configuration. (Also requires `monitoring_enable`)
shelly_enable: true
# shelly_plug_hostname: 192.168.88.34
# shelly_plug_http_username: username
# shelly_plug_http_password: "password"

# AirGradient configuration. (Also requires `monitoring_enable`)
airgradient_enable: false

# Starlink configuration. (Also requires `monitoring_enable`)
starlink_enable: false

prometheus_monitor_prometheus: true

domain_name_enable: false

# prometheus_node_exporter_targets: []
#  - 'pihole.int.stangl.co.za:9100'
#  - 'monitoring.int.stangl.co.za:9100'
#  - 'music.int.stangl.co.za:9100'
#  - 'hass.int.stangl.co.za:9100'

prometheus_extra_scrape_configs: >
  - job_name: 'essential-hosts'
    metrics_path: /probe
    scrape_interval: 5s
    params:
      module: [icmp]  # Look for a HTTP 200 response.
    file_sd_configs:
      - files:
          - essential-hosts.yaml
    relabel_configs:
      - source_labels: [__address__]
        regex: '(.*);(.*)'  # first is the url, thus unique for instance
        target_label: instance
        replacement: $1
      - source_labels: [__address__]
        regex: '(.*);(.*)'  # second is humanname to use in charts
        target_label: humanname
        replacement: $2
      - source_labels: [instance]
        target_label: __param_target
      - target_label: __address__
        replacement: ping:9115  # The blackbox exporter's real hostname:port.

  - job_name: 'lab-hosts'
    metrics_path: /probe
    scrape_interval: 5s
    params:
      module: [icmp]  # Look for a HTTP 200 response.
    file_sd_configs:
      - files:
          - lab-hosts.yaml
    relabel_configs:
      - source_labels: [__address__]
        regex: '(.*);(.*)'  # first is the url, thus unique for instance
        target_label: instance
        replacement: $1
      - source_labels: [__address__]
        regex: '(.*);(.*)'  # second is humanname to use in charts
        target_label: humanname
        replacement: $2
      - source_labels: [instance]
        target_label: __param_target
      - target_label: __address__
        replacement: ping:9115  # The blackbox exporter's real hostname:port.

  - job_name: 'shelly-devices'
    metrics_path: /probe
    scrape_interval: 5s
    params:
      module: [icmp]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
          - dining-room-plus.int.stangl.co.za
          - family-room-plug.int.stangl.co.za
          - family-room-lights.int.stangl.co.za
          - fridge-plug.int.stangl.co.za
          # - frontgate-strikelock.int.stangl.co.za
          - garage-lights.int.stangl.co.za
          - jax-bedroom-plug.int.stangl.co.za
          - jax-desk-psu.int.stangl.co.za
          - kitchen-appliances.int.stangl.co.za
          - kitchen-counter-plug.int.stangl.co.za
          - lounge-plug.int.stangl.co.za
          - lounge-extra-plug.int.stangl.co.za
          - lounge-equipment.int.stangl.co.za
          - main-bedroom-plug.int.stangl.co.za
          - main-db-em.int.stangl.co.za
          - office-plug.int.stangl.co.za
          - office-hvac.int.stangl.co.za
          # - shelly-office-pendant-light.int.stangl.co.za
          - shelly-office-light-switch.int.stangl.co.za
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: ping:9115

  - job_name: 'hass'
    scrape_interval: 10s
    scheme: https
    metrics_path: /api/prometheus
    tls_config:
      insecure_skip_verify: true
    bearer_token: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiIyYjNhMzY1N2NiN2Q0ZjhkYTdhM2ZhYzVhZWJkNTY4MCIsImlhdCI6MTYzNTkyMzA2OCwiZXhwIjoxOTUxMjgzMDY4fQ.onoyissJySkVrQVckg8NQfFlNzKgkEVngzaOgRan1cI"
    static_configs:
      - targets:
        - "hass.int.stangl.co.za"

  - job_name: 'nodes'
    scrape_interval: 30s
    scrape_timeout: 15s
    static_configs:
      - targets:
        - 'zimaboard.int.stangl.co.za:9100'
        - 'hass.int.stangl.co.za:9100'
        - 'plex.int.stangl.co.za:9100'
