{
 "title": "Overview",
 "description": "Quick overview",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "5s,10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "targets",
    "query": {
     "query": "label_values(probe_success, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "All devices",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "shelly_power", "legendFormat": "{{ name }}" }
   ]
  },
  {
   "title": "Bare Metal Server Probes (Up/Down) - Current",
   "type": "table-old",
   "gridPos": { "h": 12, "w": 9, "x": 13, "y": 0 },
   "targets": [
    {
     "expr": "probe_success{instance!~\"(desktop|macmini).+\"}"
    }
   ]
  },
  {
   "title": "Last Restart",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bottomk(1, sum by (kubernetes_node) (time() - node_boot_time_seconds))"
    }
   ]
  },
  {
   "title": "Speedtest",
   "type": "graph",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bps", "label": "Speed" }
   ],
   "targets": [
    {
     "expr": "speedtest_download_bits_per_second",
     "legendFormat": "Download Speed"
    },
    {
     "expr": "speedtest_upload_bits_per_second",
     "legendFormat": "Upload Speed"
    }
   ]
  },
  { "title": "SSL cert expiry", "type": "table-old", "gridPos": { "h": 5, "w": 11, "x": 13, "y": 12 } },
  { "title": "LE certs cert-manager", "type": "table-old", "gridPos": { "h": 4, "w": 11, "x": 13, "y": 17 } },
  {
   "title": "Speedtest",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "ms", "label": "Speed" }
   ],
   "targets": [
    {
     "expr": "speedtest_ping_latency_milliseconds",
     "legendFormat": "Latency"
    },
    {
     "expr": "speedtest_jitter_latency_milliseconds",
     "legendFormat": "Jitter"
    }
   ]
  },
  {
   "title": "Bare Metal Server Probes (Up/Down) - Historic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "probe_success", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Probe Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds{instance!=\"desktop.int.stangl.co.za\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "DNS Lookup",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "probe_dns_lookup_time_seconds", "legendFormat": "{{instance}}" }
   ]
  }
 ]
}