---
port: 9123
requestTimeout: 5s
scrapeInterval: 10s
devices:
  - IPAddress: "coffee-station-plug.int.stangl.co.za"
    displayName: "CoffeeStation"
    type: "1pm"
  - IPAddress: "family-room-plug.int.stangl.co.za"
    displayName: "FamilyRoomPlug"
    type: "1pm"
  - IPAddress: "family-room-lights.int.stangl.co.za"
    displayName: "FamilyRoomLights"
    type: "dimmer2"
  - IPAddress: "fridge-plug.int.stangl.co.za"
    displayName: "Fridge"
    type: "1pm"
  - IPAddress: "jax-bedroom-plug.int.stangl.co.za"
    displayName: "JaxBedroom"
    type: "1pm"
  - IPAddress: "kitchen-appliances.int.stangl.co.za"
    displayName: "KitchenAppliances"
    type: "1pm"
  - IPAddress: "kitchen-counter-plug.int.stangl.co.za"
    displayName: "KitchenCounter"
    type: "1pm"
  - IPAddress: "lounge-plug.int.stangl.co.za"
    displayName: "LoungePlug"
    type: "1pm"
  - IPAddress: "lounge-extra-plug.int.stangl.co.za"
    displayName: "LoungeExtraPlug"
    type: "1pm"
  - IPAddress: "maids-room-plug.int.stangl.co.za"
    displayName: "MaidsRoom"
    type: "1pm"
  - IPAddress: "main-bedroom-plug.int.stangl.co.za"
    displayName: "BedroomPlug"
    type: "1pm"
  - IPAddress: "office-plug.int.stangl.co.za"
    displayName: "OfficePlug"
    type: "1pm"
  - IPAddress: "office-hvac.int.stangl.co.za"
    displayName: "OfficeHVAC"
    type: "1pm"
  - IPAddress: "main-db-em.int.stangl.co.za"
    displayName: "MainDB"
    type: "em"
